language: node_js
node_js:
- 12.10.0
cache: npm
before_install: cd frontend
script:
- npm install
- npm run build
deploy:
  provider: heroku
  app: platon-frontend
  on: frontend-dev
  skip_cleanup: true
  api_key:
    secure: pgUrl+avpRFrnSs+soUFbmQT6OMIfljsGR/IRpOXK2rqBFPYRUveMHfWrYwoa8iTchurfAVpoT0Ty/42UgRVxI72iMRovVQKwWTRrNtnNepagpLWDnsMj6A9GKXSrSTlia3rR7WcbEXwfeqI2Ldi1a7PP6rS8sIeR9f187NgpOMqcWSrX2ztfhxfnIKw7GtTru857r/JMZdWpEGepcBOvzkNhdAk2D8otq5zjBMaz2+j/gYHRVt2O/A8ncmAsx7BiAq3cLHr0zOan0VfBfAE67O6w+Lfty5+Tpv5xW8eMDwmtWokM0ND7Uhc5AzrUT+6/RIcJeXLvzJBaL/noPKLuRjXh4ZOVZDR3gdueoPzI4Q9yjvof3Mt3FmULLrm/UcZJne6lnflclkaaizkLt2iA315P0Z1hEl1SW3cNBZKexfcNL55utk8x/0u7RIwtjdk/smjOR7JVKD03EMm+/LD39EzW+Ml+0Hc6+asB4YWrAeIKvhEkm8Mia4XifEdkN3/FGK6X69xzkon07k6cw8/e8UYyp3iI6OuiODY1dG3dQS5oSzoI9fxsvb95ViFoVOziL6oNs7oIHJ3fmJtrraSVf6+LbiDxKpEM6AjFbktODA3uXkHQleURWMUllZe+ZIjtYB0tLqB+4h175d+fCL5v5iRP2xM/e8VhyLufbQFM9s=
