language: node_js
node_js:
- 12.10.0
cache: npm

before_install: cd frontend



script:
  - npm install
  - npm run build
  
deploy:
  provider: heroku
  app: platon-frontend
  api_key:
    secure: "839bb11a-4f34-4398-89b1-e2ba93f589af"