jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      before_install:
        - cd Platon/backend
      install:
        - pip install -r requirements.txt
      script:
        - python test.py
    
    - stage: test
      language: node_js
      node_js:
        - 12.10.0
      before_install:
        - cd Platon/frontend
      install:
        - npm cache clean --force
        - npm install
        - npm run build
    
    - stage: deploy
      if: branch = release AND type != pull_request
      language: python
      addons:
        ssh_known_hosts: 3.127.150.96
      python:
        - 3.6
      before_script:
        - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      script: ssh deploy-user@3.127.150.96 'bash ~/deploy.sh'
      
notifications:
  email: false
