language: node_js
node_js:
- 12.10.0
cache: npm
before_install: cd frontend
script:
- npm install
- npm run build
deploy:
  provider: heroku
  app: platon-frontend
  on: frontend-dev
  skip_cleanup: true
  api_key:
    secure: PkpfreVzOzWEMEt8nRX6sm6dDn+TelCEd9s5mS77lLhIs6nZktk0REbFvh3AdEml+4Zea4P6ta3I9dGYJSopSuoPF/R8a0+hJ8W1TfQj0CYE74u/8I9rEZy81/9btV7o9itnZSiLGx/IzqBAv0bAGxItASQN6IjczFImEQUNqhHl6WbXHX7dSPPtBZbNeVao8GMr1Ah2sCdgUis2kr6vlvx3rTRT5lcUCS3x6x0ju73ts7r31JTNE/cIzSEgrvhzbzHpsR1RCWwaWCAr+UrbOLN2MnWPavx0tBsMomrFli8p42yecECG/I5sAY97N6TII+y2ez66LUw/miIKy//QLF6pbB1/Rb6yNaWOiSLGdkRQJaJOERQD9YYr7yry08r0Wzwc9hbD0WqNckEIDuTJBtQ2q2naGgWKURE71ypfLUlzqCaKbv6A5Fw/hV9XuVgTep4/CVpXy8LsmDWnzDEVPsuqGOw0kcNrPNJhShGnwhyvN2uqlOzI+BU7AShrDupMPsghgEgCjoZr/foWc5YlnnGWmkz8AH75SErrTmk2KUCwy4IqUVVH2k+jHHBVnnJSLVx3Ahe7SgT4xaLKFvUazCk4AjrPQEafrRcL2LEJllEVWPelwzsZBEKI2qUO20+d4afhYMNhUgh3WViMkq6sefVoH9NjNT22C/6SgVNKj1E=
