language: node_js
node_js:
- 12.10.0
cache: npm

before_install: cd frontend



script:
  - npm install
  - npm run build
  
deploy:
  provider: heroku
  app: platon-frontend
  api_key:
    secure: 1e6a47d6-6d55-4a98-b89e-7956ebc29f2c