language: node_js
node_js:
- 12.10.0
cache: npm
before_install: cd frontend
script:
- npm install
- npm run build
deploy:
  provider: heroku
  app: platon-frontend
  on: frontend-dev
  skip_cleanup: true
  api_key:
    secure: lsjbVa0cQGUyXS5LQDqOw83UAu0/uNS82p/8zqW8cNKMjZvoRtFSwOCY9yH4j4s3VmlpKxeJ78ekNy897BgnV49wVJwB6K1d0UUQbPr4S8NWV0gmrs2HYqg37zDkaJ1OmI/9H56qnTsAYnKnKhZTniXGqYnqRzvMh3z0nLq3if8+vFS+xpzuJ0+dZ2oX4K4llkFZRCvT6HHLx8LSYCC8vZfr/Ss58OKg2yZhbmfG/sMPpzm0nSA5cW6k+jnvmF9qq4ZyvnPqo7yNp1XN7jkqKt3ssLtZDFSFWA6n9z13UqWU/tG2ZElcCvhyPcWFSD9EMVUt+u9l0UklKcELZ9scslMWO74SZy3pBXt3duOIXDuJChNw75U1ccHGkVoVELRMg4HX5pwQQlVPZ9fKgGsZrGvUuygAWy2D+qWu0sfwnBbsbFJvzce1xR/PfNOgJmfqgYsdI/pp/zYpBaTJvUjqkdTrErnYuddFgyrfUbLpz4qbLfw2XTtpBsSQfeINuxU3s6Xz6/hAbWv3lDp0wTcsBp5whBOth3hOyPvOsv3/drdt0m7odj/RZDLl+kRAagymAFEbf3j0bVKF5on1gUInSXV3+4lq55cA+60eicJBPC+FxMyBGyL0ekmDOOI8lqdSfizYg0c/GjDMAsMJ7+F0nDAIM6VZJ0ZhQcosSsjxmy0=
