language: node_js
node_js:
- 12.10.0
cache: npm
before_install: cd frontend
script:
- npm install
- npm run build
deploy:
  provider: heroku
  app: platon-frontend
  api_key:
    secure: EfH3LAPawyic6gxJLNHOq4uIb+K0jUmLhqeBNLy/5gpEGhh6b9A5hGj5YxZ/KcR4zTki6R6r7PE4bcCi6tJ7IbMtmaNr2j6vX5YDnWNGfKb6vv7jJ3q/nFfKJ3iEdVORuEyl9+RcmEgAQErzNn+FT1cBvCa0L0GldzftabVaLvlZyor7a4QlhoO1oPm8gSr4hhEBvJ/4DfzY7VNGHBSpcwnVGuxtILT8TRSFlEOkT3yPRYBcUDeq9Jn8jl2tX5o5Ks3JouWWaa4EkzI+q1p9pYOYXIqDQE50uPGSP7luTiKZfCxzy8dnZDr+BPL7clbaeucmEF5Md+5LYjt59/kXie1MbFxj8p2bZy0S3oMfzJMcoVsiZ66ltzRfMbvmMbdy6aSIP0t4CTGMITo9AuvIYb0s/lpdCcDDYd8BDacVuDcpcyV9r26nzD1wHGIJkiZAC50LgvHrPSB9vD09jtdLQW73wPWtPZcfQ3ckpkra6RSflz+hxVB68eUYkvw0SdtBvlTH+aKDOv+yqJSwBjk432HOThlOyoy3w5w45v3CIyochaN1AfjJjqjLbE7lwSRBC6g4ZCit6U6sVO4BZZjDIB7MQhW+dGZ098WBsdc9niZFcLJXw/C5g7ciV7jq3eAxnfyVs5xwax+FDLQC3eBrQa8SqeGCf2x12Ud7TSoI4lw=
