matrix:
  include:
    - language: python
    - before_script:
      - cd Platon/backend
    script:
      - python test.py
    
    - language: node_js
      node_js:
        -12.10.0
      cache: npm
      before_script:
        - cd Platon/backend
      script:
        - npm cache clean --force
        - npm install
        - npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh deploy-user@52.59.254.130 'bash ./deploy.sh'
  on:
    branch: frontend-release