language: node_js
node_js:
- 12.10.0
cache: npm

before_install: cd frontend



script:
  - npm install
  - npm run build
  
deploy:
  provider: heroku
  app: platon-frontend
  api_key:
    secure: "f0d74a8b-9f63-44a1-9393-06186f245f69"