"""initial migration

Revision ID: 2e5cd3b20b15
Revises: 41b69090945e
Create Date: 2020-11-12 10:59:37.726282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e5cd3b20b15'
down_revision = '41b69090945e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='follows_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
