"""empty message

Revision ID: 2f7f73d65b09
Revises: 9868dd7416dc
Create Date: 2020-12-18 19:56:25.191839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f7f73d65b09'
down_revision = '9868dd7416dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upcoming_events', 'location',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.drop_index('location', table_name='upcoming_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('location', 'upcoming_events', ['location'], unique=True)
    op.alter_column('upcoming_events', 'location',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    # ### end Alembic commands ###
