"""initial migration

Revision ID: 41b69090945e
Revises: 
Create Date: 2020-11-12 10:56:30.373528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41b69090945e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researchinformation')
    op.drop_table('follows')
    op.drop_index('e_mail', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('e_mail', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('password_hashed', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('surname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('profile_photo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('google_scholar_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('researchgate_name', mysql.VARCHAR(length=50), nullable=True),
    sa.CheckConstraint('(`is_private` in (0,1))', name='users_chk_2'),
    sa.CheckConstraint('(`is_valid` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('e_mail', 'users', ['e_mail'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='follows_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('researchinformation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('research_title', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('type', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='researchinformation_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
