"""migration_trial

Revision ID: 7e552cf3a4c0
Revises: 
Create Date: 2020-11-12 00:53:38.204455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e552cf3a4c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_mail', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('password_hashed', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('profile_photo', sa.String(length=50), nullable=True),
    sa.Column('google_scholar_name', sa.String(length=50), nullable=True),
    sa.Column('researchgate_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('e_mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
