"""empty message

Revision ID: b3c507e3460c
Revises: 
Create Date: 2020-12-19 14:04:34.594362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3c507e3460c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_requirements', sa.Column('requirement_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspace_requirements', 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workspace_requirements', 'requirements')
    op.alter_column('workspaces', 'max_collaborators',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.drop_constraint('workspaces_ibfk_1', 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key('workspaces_ibfk_1', 'workspaces', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workspaces', 'max_collaborators',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.add_column('workspace_requirements', sa.Column('requirements', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'workspace_requirements', type_='foreignkey')
    op.drop_column('workspace_requirements', 'requirement_id')
    # ### end Alembic commands ###
