"""empty message

Revision ID: c4ad8a20e9bf
Revises: b3c507e3460c
Create Date: 2020-12-21 18:08:21.533827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ad8a20e9bf'
down_revision = 'b3c507e3460c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contributions_ibfk_1', 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('workspaces_ibfk_1', 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key('workspaces_ibfk_1', 'workspaces', 'users', ['creator_id'], ['id'])
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key('contributions_ibfk_1', 'contributions', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
