"""empty message

Revision ID: db1de3bfc196
Revises: 2f7f73d65b09
Create Date: 2020-12-18 20:01:55.970596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1de3bfc196'
down_revision = '2f7f73d65b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('acronym', table_name='upcoming_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('acronym', 'upcoming_events', ['acronym'], unique=True)
    # ### end Alembic commands ###
