# Generated by Django 3.0.5 on 2020-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('password_hashed', models.CharField(max_length=64)),
                ('e_mail', models.EmailField(max_length=250, unique=True)),
                ('token', models.CharField(max_length=64, null=True)),
                ('about_me', models.TextField(max_length=330)),
                ('job_uuid', models.CharField(max_length=32)),
                ('field_of_study', models.CharField(max_length=50)),
                ('forget_password_ans', models.CharField(max_length=50)),
            ],
        ),
    ]
