from unittest import TestCase
import json
from app.upcoming_events.helpers import UpcomingEventsManager
class UpcomingEventsTest(TestCase):

    def test_parse_event(self):
        first_part = '<tr bgcolor="#f6f6f6">\n<td rowspan="2" align="left"><a href="/cfp/servlet/event.showcfp?eventid=120227&amp;copyownerid=113056">HB 4.1 2021</a></td>\n<td align="left" colspan="3">Humanities Bulletin, Volume 4, Number 1, May 2021, UK</td><td align="center" rowspan="2"><input type="checkbox" name="eventid_120227"></td>\n</tr>'
        second_part = '<tr bgcolor="#f6f6f6">\n<td align="left">N/A</td>\n<td align="left">N/A</td>\n<td align="left">Apr 25, 2021</td>\n</tr>'
        actual_result = UpcomingEventsManager.parse_event(first_part,second_part)
        expected_result = {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120227&amp;copyownerid=113056',
                           'acronym': 'HB 4.1 2021',
                           'title': 'Humanities Bulletin, Volume 4, Number 1, May 2021, UK',
                           'date': 'N/A',
                           'location': 'N/A',
                           'deadline': 'Apr 25, 2021'}
        self.assertEqual(actual_result,expected_result)

    def test_get_number_of_pages(self):
        expected_result = 10
        actual_result = UpcomingEventsManager.get_number_of_pages()
        self.assertEqual(expected_result,actual_result)

    def test_parse_page(self):
        expected_result = [{'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120268&amp;copyownerid=46167',
                            'acronym': 'ICCIoT 2021',
                            'title': '2nd International Conference on Cloud and Internet of Things ',
                            'date': 'Jan 23, 2021 - Jan 24, 2021',
                            'location': 'Zurich, Switzerland',
                            'deadline': 'Dec 19, 2020'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120267&amp;copyownerid=166599',
                            'acronym': 'ISAIC 2021',
                            'title': 'The 2nd International Symposium on Automation, Information and Computing (ISAIC 2021)',
                            'date': 'Dec 3, 2021 - Dec 6, 2021',
                            'location': 'Beijing Jiaotong University, China',
                            'deadline': 'Oct 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120261&amp;copyownerid=166599',
                            'acronym': 'ISWEE 2021',
                            'title': 'The 2nd International Symposium on Water, Ecology and Environment  (ISWEE 2021)',
                            'date': 'Oct 15, 2021 - Oct 18, 2021',
                            'location': 'Beijing Jiaotong University, China',
                            'deadline': 'Aug 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120260&amp;copyownerid=166599',
                            'acronym': 'BECB 2021',
                            'title': '2021 International Symposium on Biomedical Engineering and Computational Biology (BECB 2021)',
                            'date': 'Aug 13, 2021 - Aug 15, 2021',
                            'location': 'Beihang Univeristy, Beijing, China',
                            'deadline': 'Jun 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120259&amp;copyownerid=28088',
                            'acronym': 'Internet of things 2021',
                            'title': 'CALL FOR BOOK CHAPTERS : Internet of Things: A Hardware Development Perspective',
                            'date': 'N/A',
                            'location': 'N/A',
                            'deadline': 'Jan 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120258&amp;copyownerid=160088',
                            'acronym': 'SOCS 2021',
                            'title': 'The 14th Annual Symposium on Combinatorial Search',
                            'date': 'Jun 12, 2021 - Jun 14, 2021',
                            'location': 'Guangzhou, China',
                            'deadline': 'Feb 14, 2021 (Feb 10, 2021)'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120257&amp;copyownerid=18301',
                            'acronym': 'CICE 2021',
                            'title': 'Canada International Conference on Education',
                            'date': 'Jun 22, 2021 - Jun 24, 2021',
                            'location': 'Virtual Conference',
                            'deadline': 'Feb 15, 2021 (Feb 1, 2021)'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120256&amp;copyownerid=90512',
                            'acronym': 'Scopus-WSCIS 2021',
                            'title': 'The 2nd International Workshop on Smart City and Intelligent Systems (WSCIS 2021)',
                            'date': 'Sep 23, 2021 - Sep 25, 2021',
                            'location': 'Wuhan, China',
                            'deadline': 'Mar 25, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120255&amp;copyownerid=96880',
                            'acronym': 'Scopus-BDAI 2021',
                            'title': 'The 3rd International Conference on Industrial Applications of Big Data and Artificial Intelligence (BDAI 2021)',
                            'date': 'Sep 23, 2021 - Sep 25, 2021',
                            'location': 'Wuhan, China',
                            'deadline': 'Mar 25, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120254&amp;copyownerid=96880',
                            'acronym': 'Scopus-BDAI 2021',
                            'title': 'The 3rd International Conference on Industrial Applications of Big Data and Artificial Intelligence (BDAI 2021)',
                            'date': 'Sep 23, 2021 - Sep 25, 2021',
                            'location': 'Wuhan, China',
                            'deadline': 'Mar 25, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120233&amp;copyownerid=76517',
                            'acronym': 'SDP Shared Tasks 2021',
                            'title': '2nd Workshop on Scholarly Document Processing (SDP 2021) @ NAACL Shared Tasks',
                            'date': 'Jun 10, 2021 - Jun 10, 2021',
                            'location': 'Mexico City, Mexico',
                            'deadline': 'Mar 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120227&amp;copyownerid=113056',
                            'acronym': 'HB 4.1 2021',
                            'title': 'Humanities Bulletin, Volume 4, Number 1, May 2021, UK',
                            'date': 'N/A',
                            'location': 'N/A',
                            'deadline': 'Apr 25, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120201&amp;copyownerid=166583',
                            'acronym': 'SOUPS 2021',
                            'title': 'The Seventeenth Symposium on Usable Privacy and Security',
                            'date': 'Aug 8, 2021 - Aug 10, 2021',
                            'location': 'Vancouver, B.C., Canada',
                            'deadline': 'Feb 25, 2021 (Feb 18, 2021)'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120185&amp;copyownerid=163134',
                            'acronym': 'PhSR 2021',
                            'title': 'CFP: Philosophy and Sonic Research: Thinking with Sounds and Rhythms',
                            'date': 'N/A',
                            'location': 'N/A',
                            'deadline': 'Apr 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120184&amp;copyownerid=106070',
                            'acronym': 'LION 2021',
                            'title': 'Learning and Intelligent Optimization',
                            'date': 'Jun 20, 2021 - Jun 25, 2021',
                            'location': 'Athens, Greece',
                            'deadline': 'Feb 15, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120183&amp;copyownerid=53502',
                            'acronym': 'Scotocracy 2020',
                            'title': 'Scotocracy',
                            'date': 'N/A',
                            'location': 'N/A',
                            'deadline': 'TBD'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120145&amp;copyownerid=166570',
                            'acronym': 'ARTHRIC 2021',
                            'title': 'Art and Human Rights International Conference',
                            'date': 'May 20, 2021 - May 21, 2021',
                            'location': 'Lisbon',
                            'deadline': 'Dec 18, 2020'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120130&amp;copyownerid=13149',
                            'acronym': 'ICCSA 2021',
                            'title': '21st International Conference on Computational Science and its Applications',
                            'date': 'Jul 5, 2021 - Jul 8, 2021',
                            'location': 'Cagliari, Italy',
                            'deadline': 'Mar 28, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120109&amp;copyownerid=59874',
                            'acronym': 'Convivial Cultures 2021',
                            'title': 'XI Lisbon Summer School for the Study of Culture - Convivial Cultures',
                            'date': 'Jun 28, 2021 - Jul 3, 2021',
                            'location': 'Lisbon, Portugal',
                            'deadline': 'Feb 21, 2021'},
                            {'link': 'http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=120108&amp;copyownerid=166567',
                            'acronym': 'Heavy Vehicle Technology 2021',
                            'title': 'Autonomous and Connected Heavy Vehicle Technology',
                            'date': 'Apr 1, 2021 - Apr 2, 2021',
                            'location': 'Dehradun,India',
                            'deadline': 'Feb 15, 2021 (Jan 15, 2021)'}]
        actual_result = UpcomingEventsManager.parse_page(2)
        self.assertEqual(expected_result,actual_result)