version: '3'
    
services:
  db:
    image: mysql:8.0.20
    environment:
        MYSQL_DATABASE: 'localdb'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'admin'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'Localhost.123'
        # Password for root access
        MYSQL_ROOT_PASSWORD: '179346285'
    ports:
      - "3302:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db